mysite/UWFinancePlanner/urls.py
from django.conf.urls import url

from . import views

#TODO rework URL structure
app_name = 'UWFinancePlanner'
urlpatterns = [
    url(r'^$', views.index, name='index2'),
    url(r'^addSpending/$', views.addSpending, name='addSpending'),
    url(r'^deleteSpending/(?P<spending_id>[0-9]+)/$', views.deleteSpending, name='deleteSpending'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^login$', views.login_view, name='login_view'),
    url(r'^loginAction$', views.loginAction, name='loginAction'),
    url(r'^(?P<user>.+)/(?P<year>[0-9]+)/(?P<month>[0-9]+)$', views.index_dateTime, name='index'),
    url(r'^(?P<user>.+)$', views.index_user, name='index'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^UWFinance/', include('UWFinancePlanner.urls'))
]

mysite/UWFinancePlanner/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
import re
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser

class Nutzer(AbstractUser):
    chatID = models.CharField(max_length=200, default='0')
    budget = models.DecimalField(default=0, max_digits=20, decimal_places=2)
    #def __str__(self):
        #return self.name

class Tag(models.Model):
    class Meta:
           ordering = ['name']
    rgbVali = RegexValidator(r'^[0-9]+,[0-9]+,[0-9]+$', 'Enter RGB values: 0,0,0 - 255,255,255')
    name = models.CharField(max_length=200)
    rgb = models.CharField(max_length=25, default='0,0,0', validators=[rgbVali])
    superiorCategory = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    def __str__(self):
        if self.superiorCategory is None:
            return self.name
        else:
            return self.superiorCategory.name + ' - ' + self.name

class Tag_regex(models.Model):
    regex = models.CharField(max_length=500)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    def __str__(self):
        return self.tag.name + ' - ' + self.regex

class Location(models.Model):
    name = models.CharField(max_length=200)
    latitude = models.DecimalField(max_digits=15, decimal_places=10, default=0)
    longitude = models.DecimalField(max_digits=15, decimal_places=10, default=0)
    def __str__(self):
        return self.name

class Buchung(models.Model):
    nutzer = models.ForeignKey(Nutzer, null=True, default=1, on_delete=models.CASCADE)
    beschreibung = models.CharField(max_length=200)
    betrag = models.DecimalField(max_digits=15, decimal_places=2)
    location = models.ForeignKey(Location, null=True, on_delete=models.CASCADE)
    datum = models.DateTimeField(default=timezone.now)
    tag = models.ForeignKey(Tag, null=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.beschreibung

mysite/UWFinancePlanner/views.py
from datetime import datetime
import json
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from .models import Buchung, Nutzer, Tag, Location
from django.shortcuts import redirect
from UWFinancePlanner import helper_statistics, helper_getter
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse

def login_view(request):
    return render(request, 'UWFinancePlanner/login.html')

def loginAction(request):
    user = request.POST['username']
    pw = request.POST['password']
    user = authenticate(username = user, password = pw)
    if user is not None:
        login(request, user)
        target  = '/UWFinance/' + str(user)
        return redirect(target)
    else:
        return render(request, 'UWFinancePlanner/login.html')

def logout_view(request):
    logout(request)
    return render(request, 'UWFinancePlanner/login.html')

@login_required
def index_user(request, user):
    context = getContext(datetime.now().year, datetime.now().month, user)
    return render(request, 'UWFinancePlanner/index.html', context)

@login_required
def index_dateTime(request, user, year, month):
    context = getContext(int(year), int(month), user)
    return render(request, 'UWFinancePlanner/index.html', context)

@login_required
def index(request):
    context = getContext(datetime.now().year, datetime.now().month, Nutzer.objects.all().first())
    return render(request, 'UWFinancePlanner/index.html', context)

def getContext(year, month, user):
    buchungen_list = Buchung.objects.order_by('datum')
    buchungen_filtered = []
    for buchung in buchungen_list:
        if buchung.datum.year == year and buchung.datum.month == month:
            if buchung.nutzer.username == user:
                buchungen_filtered.append(buchung)
    cats = helper_statistics.calculateCategories(buchungen_filtered)
    ub = Nutzer.objects.get(username = user)
    budget_config = ub.budget
    budget = [str(budget_config) for x in range(len(buchungen_filtered))]
    saldo = []
    average = []
    tmp = 0
    yAxis = []
    tooltip = []
    categoryValues = []
    categories = []
    for buch in buchungen_filtered:
        tmp = tmp + buch.betrag
        saldo.append(str(tmp))
        yAxis.append(str(buch.datum))
        tooltip.append(buch.beschreibung)
        average.append(helper_statistics.calculateAverageSpending(budget_config, year, month, buch.datum.day))
    average.append(helper_statistics.calculateAverageSpending(budget_config, year, month, datetime.now().day))
    yAxis.append(str(datetime.now()))
    listCats = cats.keys()
    listCatsVs = cats.values()
    for cat in listCats:
        categories.append(cat.name)
    for value in listCatsVs:
        categoryValues.append(str(value))
    nextMonth = month + 1
    nextYear = year
    prevMonth = month - 1
    if month == 12:
        nextMonth = 1
        nextYear = year + 1
    if month == 1:
        prevYear = year - 1
        prevMonth = 12
    locations = Location.objects.all()
    context = {
        'location_list': locations,
        'spendings_list': buchungen_filtered,
        'user': user,
        'saldo': saldo,
        'budget': budget,
        'yAxis': yAxis,
        'tooltip': json.dumps(tooltip),
        'average': average,
        'prevMonth': prevMonth,
        'nextMonth': nextMonth,
        'prevYear': year,
        'nextYear': nextYear,
        'categories': json.dumps(categories),
        'category_values': categoryValues,
        'categoryColors': helper_getter.getCategoryColors(categories),
    }
    return context

@login_required
def addSpending(request):
    try:
        amount = request.POST['amount']
        what = request.POST['what']
        where = request.POST['where']
        locations = Location.objects.filter(name=where)
        if not locations:
            location = Location(name=where)
            location.save()
        else:
            location = locations[0]
        who = Nutzer.objects.filter(username=request.user)[0]
        newBuchung = Buchung(nutzer = who, beschreibung = what, betrag = amount,
            location = location)
        newBuchung.save()
    except (KeyError):
        return HttpResponse(KeyError)
    return HttpResponseRedirect(reverse('UWFinancePlanner:index', kwargs={'user':request.user}))

def deleteSpending(request, spending_id):
    spending = get_object_or_404(Buchung, pk=spending_id)
    spending.delete()
    return HttpResponseRedirect(reverse('UWFinancePlanner:index', kwargs={'user':request.user}))

mysite/UWFinancePlanner/templates/UWFinancePlanner/index.html
<html>

  <head>

    {% load staticfiles %}
    <title>Money</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <script src="{% static 'UWFinancePlanner/Chart.js' %}"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>

    <a href="{% url 'UWFinancePlanner:logout' %}"><button type="button" class="btn btn-danger"><i class="fas fa-sign-out-alt"></i> Logout</button></a>

    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalCenter">
      <i class="fas fa-plus"></i> Add expense
    </button>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Add expense</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'UWFinancePlanner:addSpending' %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="amount">Amount spent: </label>
            <input id="amount" type="number" name="amount" class="form-control" aria-describedby="amountHelp" placeholder="9.95" step="0.01">
            <small id="amountHelp" class="form-text text-muted">How much did you spent?</small>
          </div>
          <div class="form-group">
            <label for="what">What? </label>
            <input id="what" type="text" name="what" class="form-control" aria-describedby="whatHelp" placeholder="Food">
            <small id="whatHelp" class="form-text text-muted">...and for what?</small>
          </div>
          <div class="form-group">
            <label for="where">Where? </label>
            <input id="where" name="where" list="locations_list" class="form-control" aria-describedby="whatHelp" placeholder="Lidl">
            <datalist id="locations_list">
              {% for location in location_list %}
              <option value="{{ location.name|safe }}">
              {% endfor %}
            </datalist>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      </div>
    </div>
  </div>
</div>

<script>

var userLat = 0.0;
var userLong = 0.0;
var locations = [];

{% for location in location_list %}
  locations.push({name:"{{ location.name|safe }}", lat:"{{ location.latitude|safe }}", long:"{{ location.longitude|safe }}"});
{% endfor %}

function getDistanceFromLatLonInKm(lat1,lon1,lat2,lon2) {
  var R = 6371; // Radius of the earth in km
  var dLat = deg2rad(lat2-lat1);  // deg2rad below
  var dLon = deg2rad(lon2-lon1);
  var a =
    Math.sin(dLat/2) * Math.sin(dLat/2) +
    Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) *
    Math.sin(dLon/2) * Math.sin(dLon/2)
    ;
  var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
  var d = R * c; // Distance in km
  return d;
}

function deg2rad(deg) {
  return deg * (Math.PI/180)
}

window.onload = function() {
getLocation();
};
  var x = document.getElementById("position");
  function getLocation() {
     if (navigator.geolocation) {
         navigator.geolocation.getCurrentPosition(showPosition);
     } else {
         x.innerHTML = "Geolocation is not supported by this browser.";
     }
  }
  function showPosition(position) {
    userLat = position.coords.latitude;
    userLong = position.coords.longitude;
    closetLocation = "None";
    closetLocationDistance = Number.MAX_SAFE_INTEGER;
    locations.forEach(function(element) {
      distance = getDistanceFromLatLonInKm(userLat, userLong, element.lat, element.long);
      if (closetLocationDistance > distance){
        closetLocation = element.name;
        closetLocationDistance = distance;
      }
    });
    /*x.innerHTML = "Latitude: " + position.coords.latitude +
    "<br>Longitude: " + position.coords.longitude +
    "<br>Closest Location: " + closetLocation +
    "<br>Distance: " + closetLocationDistance + "km";*/
    document.getElementById('where').value=closetLocation;
  }
</script>

  <div class="container">
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link" href="/UWFinance/{{ user }}/{{ prevYear }}/{{ prevMonth }}">Last Month</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/UWFinance/{{ user }}/{{ nextYear }}/{{ nextMonth }}">Next Month</a>
      </li>
    </ul>

    <div class="accordion" id="accordion">
      <div class="card">
        <div class="card-header" id="headingOne">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              Detailed progress
            </button>
          </h5>
        </div>

        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
          <div class="card-body">
            <canvas id="myChart" responsive=true></canvas>
        </div>
      </div>
    </div>


    <script>

    var tooltips = {{ tooltip|safe }};

    var ctx = document.getElementById("myChart").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: {{ yAxis|safe }},
            datasets: [{
                label: 'Budget',
                data: {{ budget|safe }},
                borderDash: [10],
                backgroundColor: [
                    'rgba(37, 255, 62, 0.3)',
                ]
            },
            {
                label: 'Ausgaben',
                data: {{ saldo|safe }},
                lineTension: 0.1,
                backgroundColor: [
                    'rgba(255, 0, 0, 0.8)',
                ]
            },
            {
                label: 'Ideallinie',
                data: {{ average }},
                borderDash: [10],
                backgroundColor: [
                    'rgba(245, 245, 60, 0.8)',
                ]
            },
          ]
        },
        options: {
          tooltips: {
              mode: 'nearest',
              intersect: false,
              callbacks: {
                label: function(tooltipItem, data) {
                  return tooltipItem.yLabel + ' €' ;
                },
                afterLabel: function(tooltipItem, data) {
                  return tooltips[tooltipItem.index];
                },
              }
          },
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero:true
                    }
                }]
            }
        }
    });
    </script>
  </div>

<div class="container" style="margin-top:10%">
  <script>$(document).ready( function () {
    $('#overview').DataTable();
    } );
    //https://www.datatables.net/
  </script>
  <h3>Spendings</h3>
  {% if spendings_list %}
    <div class="table-responsive">
      <table class="table table-hover" id="overview" data-order='[[ 3, "desc" ]]'>
        <thead>
          <th>Amount</th>
          <th>Details</th>
          <th>Where</th>
          <th>When</th>
          <th>Delete?</th>
        </thead>
        <tbody>
          {% for buchung in spendings_list %}
              <tr>
                  <td>{{ buchung.betrag }}</td>
                  <td>{{ buchung.beschreibung }}</td>
                  <td>{{ buchung.location }}</td>
                  <td>{{ buchung.datum }}</td>
                  <td>
                    <form action="{% url 'UWFinancePlanner:deleteSpending' buchung.id %}" method="post">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                  </td>
              </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% else %}
    <p>No spendings for this month available.</p>
  {% endif %}
</div>

<div class="container">
  <canvas id="cake" class="chartjs" responsive=true></canvas>
  <script>
  new Chart(document.getElementById("cake"),{
    "type":"doughnut",
    "data":{
      "labels":{{ categories|safe }},
      "datasets":[{
        "label":"Categories","data":{{ category_values|safe }},
        "backgroundColor":[{% for obj in categoryColors %}"rgb({{ obj }})",{% endfor %}]
      }]
    }
  });
  </script>
</div>


</body>
</html>

mysite/UWFinancePlanner/templates/UWFinancePlanner/login.html
{% load staticfiles %}
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'UWFinancePlanner/css.css' %}" />
</head>

<div>
  <form action="{% url 'UWFinancePlanner:loginAction' %}" method="post">
    {% csrf_token %}
      <input type="text" class="form-control" name="username" id="1" placeholder="Username"  />
      <input type="password" class="form-control" name="password" id="2" placeholder="Password"  />
      <button type="submit" class="btn btn-default">Login</button>
  </form>
</div>